### ISSUE TITLE
Preferred way of managing environments

### ISSUE THREAD

**Issue by HooDaresWins** [ingrammicro/connect-php-sdk#27]
Hello,

I'm wondering if you have any suggestion on how to filter out non-production requests in production environment.

As of now, the solution I came up with at the moment is overriding the `process()` method and filter out there, but I was wondering what would be your take on it.

Thanks for your time and greetings from Québec, Canada !

**Comment by marcserrat** [comment]
Hi!
Thanks for your question!
Currently as you properly say is not possible to filter without modifying the sdk or changing a little bit the skeleton. I have in backlog to add such filters on configuration file and would like your opinion about it.

Currently what you can do is something similar to:

$requestProcessor = new ProductRequests();
$requests = $requestProcessor->listRequests([
        'status' => ['pending'],
        'asset_connection_type' => 'production'
    ]);
foreach ($requests as $request){
    $requestProcessor->processRequest($request);
}

of course, this is quite simple and you will need to add the control.

another option, is simply not modify nothing and discard the ones that are not valid for you in your processRequest method, there you can check $request->asset->connection->type and if is not "production" just thrown a Skip for such request.

hope that helps!

**Comment by YanCoutu** [comment]
Unfortunately, the `asset_connection_type` parameter doesn't seem to work: we still get all the results. However, `asset__connection__type` and `asset.connection.type` *seem* to filter something, except we don't get any result. So either one of these should be the correct field, but we don't know what values it can take.

**Comment by marcserrat** [comment]
Hi yan,

indeed i did a mistake, since is asset.connection.type, then example will be like:
$requestProcessor = new ProductRequests();
$requests = $requestProcessor->listRequests([
'status' => 'pending',
'asset.connection.type' => 'production'
]);
foreach ($requests as $request){
$requestProcessor->processRequest($request);
}

Please see that when you use filters, all of them are cleared, and that means you may want to also add "product.id" to reduce also scope.
